server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    ##################redis##################
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1
        max-active: 200
        max-idle: 10
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000
############# mybatisplus控制台输出sql ###################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl